
const PAGE_W = 612;
const PAGE_H = 792;
const MARGIN = 48;
const CONTENT_W = PAGE_W - MARGIN * 2;
const ROWS_PER_PAGE = 30;

const rgb = (r, g, b) =>
  `${(r / 255).toFixed(3)} ${(g / 255).toFixed(3)} ${(b / 255).toFixed(3)}`;

const C = {
  green: rgb(10, 109, 61),
  greenTint: rgb(230, 244, 236),
  greenDark: rgb(5, 85, 48),
  ink: rgb(23, 35, 27),
  muted: rgb(100, 112, 103),
  border: rgb(220, 229, 222),
  rowAlt: rgb(248, 250, 247),
  white: rgb(255, 255, 255),
  black: rgb(0, 0, 0),
};

const escapePdfText = (value) =>
  String(value ?? '')
    .normalize('NFKD')
    .replace(/[^\x20-\x7E]/g, '?')
    .replace(/\\/g, '\\\\')
    .replace(/\(/g, '\\(')
    .replace(/\)/g, '\\)');

const truncate = (str, max) => {
  const s = String(str ?? '');
  return s.length > max ? s.slice(0, max - 1) + '...' : s;
};

const filledRect = (x, y, w, h, color) =>
  `${color} rg\n${x} ${y} ${w} ${h} re f\n0 0 0 rg`;

const strokedRect = (x, y, w, h, color, lineWidth = 1) =>
  `${color} RG\n${lineWidth} w\n${x} ${y} ${w} ${h} re S\n0 0 0 RG`;

const text = (str, x, y, size, color, font = 'F1') =>
  `BT\n${color} rg\n/${font} ${size} Tf\n${x} ${y} Td\n(${escapePdfText(str)}) Tj\nET`;

export const buildReportPdf = ({
  reportLabel,
  periodLabel,
  statusLabel,
  records,
  generatedAt = new Date(),
  generatedBy = 'Admin',
  reportType = 'report',
}) => {
  const statusCounts = records.reduce((acc, item) => {
    const key = item.status || 'Unspecified';
    acc[key] = (acc[key] || 0) + 1;
    return acc;
  }, {});

  const totalRecords = records.length;
  const uniqueStatuses = Object.keys(statusCounts).length;
  const generatedDateStr = generatedAt.toISOString().slice(0, 10);
  const generatedTimeStr = generatedAt
    .toISOString()
    .slice(0, 16)
    .replace('T', ' ');

  const pages = [];
  for (let i = 0; i < records.length; i += ROWS_PER_PAGE) {
    pages.push(records.slice(i, i + ROWS_PER_PAGE));
  }
  if (pages.length === 0) pages.push([]);

  const totalPages = pages.length;

  const contentStreams = pages.map((pageRows, pageIndex) => {
    const ops = [];
    const isFirstPage = pageIndex === 0;
    const pageLabel = `Page ${pageIndex + 1} of ${totalPages}`;

    ops.push(filledRect(0, PAGE_H - 78, PAGE_W, 78, C.green));
    ops.push(text('MindMatter', MARGIN, PAGE_H - 34, 18, C.white, 'F2'));
    ops.push(
      text('Platform Safety & Compliance Report', MARGIN, PAGE_H - 54, 10, C.white)
    );
    ops.push(text(pageLabel, PAGE_W - MARGIN - 70, PAGE_H - 44, 9, C.white));

    let cursorY = PAGE_H - 110;

    if (isFirstPage) {
      ops.push(text(reportLabel, MARGIN, cursorY, 18, C.ink, 'F2'));
      cursorY -= 20;

      ops.push(
        text(`Generated: ${generatedTimeStr} UTC`, MARGIN, cursorY, 9, C.muted)
      );
      cursorY -= 13;
      ops.push(
        text(`Generated by: ${generatedBy}`, MARGIN, cursorY, 9, C.muted)
      );
      cursorY -= 13;
      ops.push(
        text(
          `Period: ${periodLabel}   |   Status filter: ${statusLabel}`,
          MARGIN,
          cursorY,
          9,
          C.muted
        )
      );
      cursorY -= 24;

      /* ── KPI CARD ROW ── */
      const kpiW = (CONTENT_W - 20) / 3;
      const kpiH = 58;
      const kpiY = cursorY - kpiH;

      const kpis = [
        { label: 'TOTAL RECORDS', value: String(totalRecords) },
        { label: 'STATUS TYPES', value: String(uniqueStatuses) },
        { label: 'REPORT DATE', value: generatedDateStr },
      ];

      kpis.forEach((kpi, idx) => {
        const kpiX = MARGIN + idx * (kpiW + 10);
        ops.push(filledRect(kpiX, kpiY, kpiW, kpiH, C.greenTint));
        ops.push(filledRect(kpiX, kpiY, 3, kpiH, C.green));
        ops.push(text(kpi.value, kpiX + 14, kpiY + 32, 18, C.green, 'F2'));
      
        ops.push(text(kpi.label, kpiX + 14, kpiY + 14, 8, C.muted));
      });

      cursorY = kpiY - 26;

      ops.push(text('Status breakdown', MARGIN, cursorY, 12, C.ink, 'F2'));
      cursorY -= 18;

      Object.entries(statusCounts).forEach(([status, count]) => {
        const pct = totalRecords > 0 ? (count / totalRecords) * 100 : 0;

        ops.push(text(status, MARGIN, cursorY, 9.5, C.ink, 'F2'));
        ops.push(
          text(
            `${count} records  (${pct.toFixed(1)}%)`,
            MARGIN + 200,
            cursorY,
            9.5,
            C.muted
          )
        );
        const barW = CONTENT_W - 280;
        const barX = MARGIN + 280;
        const barH = 7;
        const barY = cursorY - 1;

        ops.push(filledRect(barX, barY, barW, barH, C.border));
        ops.push(
          filledRect(barX, barY, Math.max(2, (barW * pct) / 100), barH, C.green)
        );

        cursorY -= 22;
      });

      cursorY -= 12;
    } else {
      ops.push(text(`${reportLabel} (continued)`, MARGIN, cursorY, 13, C.ink, 'F2'));
      cursorY -= 24;
    }

    const colX = {
      name: MARGIN + 8,
      category: MARGIN + 220,
      status: MARGIN + 335,
      date: MARGIN + 425,
    };

    ops.push(filledRect(MARGIN, cursorY - 4, CONTENT_W, 20, C.greenTint));
    ops.push(strokedRect(MARGIN, cursorY - 4, CONTENT_W, 20, C.border, 0.5));

    ops.push(text('NAME', colX.name, cursorY + 2, 8, C.green, 'F2'));
    ops.push(text('CATEGORY', colX.category, cursorY + 2, 8, C.green, 'F2'));
    ops.push(text('STATUS', colX.status, cursorY + 2, 8, C.green, 'F2'));
    ops.push(text('DATE', colX.date, cursorY + 2, 8, C.green, 'F2'));

    cursorY -= 24;

    if (pageRows.length === 0) {
      ops.push(
        text(
          'No records match the selected filters.',
          MARGIN + 8,
          cursorY - 4,
          10,
          C.muted
        )
      );
    } else {
      pageRows.forEach((row, idx) => {
      
        if (idx % 2 === 0) {
          ops.push(
            filledRect(MARGIN, cursorY - 4, CONTENT_W, 18, C.rowAlt)
          );
        }

        ops.push(
          text(truncate(row.name, 34), colX.name, cursorY, 9, C.ink)
        );
        ops.push(
          text(truncate(row.category, 18), colX.category, cursorY, 9, C.muted)
        );
        ops.push(
          text(truncate(row.status, 16), colX.status, cursorY, 9, C.muted)
        );
        ops.push(
          text(row.date || '-', colX.date, cursorY, 9, C.muted)
        );

        ops.push(strokedRect(MARGIN, cursorY - 6, CONTENT_W, 0.3, C.border, 0.3));

        cursorY -= 18;
      });
    }

    ops.push(filledRect(0, 0, PAGE_W, 30, C.rowAlt));
    ops.push(
      text(
        'Generated by MindMatter Admin Portal  |  Confidential - for stakeholder review',
        MARGIN,
        11,
        7.5,
        C.muted
      )
    );

    return ops.join('\n');
  });

  const FONT_REGULAR = 3;
  const FONT_BOLD = 4;
  const FIRST_PAGE_ID = 5;

  const pageObjectIds = contentStreams.map((_, idx) => ({
    pageId: FIRST_PAGE_ID + idx * 2,
    contentId: FIRST_PAGE_ID + idx * 2 + 1,
  }));

  const objects = [];

  objects.push(`<< /Type /Catalog /Pages 2 0 R >>`);

  objects.push(
    `<< /Type /Pages /Kids [${pageObjectIds
      .map((p) => `${p.pageId} 0 R`)
      .join(' ')}] /Count ${pageObjectIds.length} >>`
  );

  objects.push(`<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>`);

  objects.push(`<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>`);

  contentStreams.forEach((stream, idx) => {
    const { pageId, contentId } = pageObjectIds[idx];

    objects.push(
      `<< /Type /Page /Parent 2 0 R ` +
        `/MediaBox [0 0 ${PAGE_W} ${PAGE_H}] ` +
        `/Resources << /Font << /F1 ${FONT_REGULAR} 0 R /F2 ${FONT_BOLD} 0 R >> >> ` +
        `/Contents ${contentId} 0 R >>`
    );

    objects.push(
      `<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`
    );
  });

  let pdf = '%PDF-1.4\n';
  const offsets = [0];

  objects.forEach((obj, idx) => {
    offsets.push(pdf.length);
    pdf += `${idx + 1} 0 obj\n${obj}\nendobj\n`;
  });

  const xrefOffset = pdf.length;
  pdf += `xref\n0 ${objects.length + 1}\n`;
  pdf += `0000000000 65535 f \n`;
  offsets.slice(1).forEach((offset) => {
    pdf += `${String(offset).padStart(10, '0')} 00000 n \n`;
  });

  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\n`;
  pdf += `startxref\n${xrefOffset}\n%%EOF`;

  const bytes = Array.from(pdf, (ch) => ch.charCodeAt(0));
  return `data:application/pdf;base64,${bytesToBase64(bytes)}`;
};

const bytesToBase64 = (bytes) => {
  const alphabet =
    'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
  let result = '';
  for (let i = 0; i < bytes.length; i += 3) {
    const b1 = bytes[i];
    const b2 = bytes[i + 1];
    const b3 = bytes[i + 2];
    result += alphabet[b1 >> 2];
    result += alphabet[((b1 & 3) << 4) | ((b2 ?? 0) >> 4)];
    result +=
      b2 === undefined
        ? '='
        : alphabet[((b2 & 15) << 2) | ((b3 ?? 0) >> 6)];
    result += b3 === undefined ? '=' : alphabet[b3 & 63];
  }
  return result;
};